Added null check for value in getFieldFromDoc in pouchdb selector core utils
pouchdb/pouchdb pull request #8027
Opened 2020-03-10 20:41 UTC by t-cho1

![Screen Shot 2020-03-10 at 1 38 34 PM](https://user-images.githubusercontent.com/6394518/76357289-a770d580-62d4-11ea-812d-bbdd27f6fee1.png)
Sometimes `value` would be undefined, so in the for loop, it would be looking for `value[key]`, which spits out `Cannot read property <property> of undefined`

2021-08-12 14:44 UTC, gaodeng commented
@daleharvey 
Can you help merge this PR ?

2021-08-12 15:33 UTC, dheimoz approved these changes

2021-08-20 01:26 UTC, gaodeng approved these changes

2021-10-19 15:47 UTC, dheimoz commented
hello @t-cho1 I am terribly sorry for the time that it has taken to get  your contribution reviewed. As you have seen, tests has ben migrated to GitHub Actions. I wonder if you can get the latest changes and apply your contribution and check should tests passed?

Thanks.

2022-02-23 11:30 UTC, AlbaHerrerias commented
Hey @t-cho1 , could you rebase from master? It will allow me to trigger Github actions. Thanks!

2023-04-03 10:36 UTC, rasgo-cc commented
Any chance to get this reviewed? 
`getFieldFromDoc` is still crashing whenever the doc is null / undefined

2023-04-03 22:04 UTC, garethbowen commented
@rasgo-cc It seems like @t-cho1 is not responding so nobody can update the PR to run the GH actions which is required to merge. Would you mind creating a new PR from `master` which this change? Then we can close this one.

2024-02-08 13:57 UTC, SourceR85 requested changes

2024-02-08 13:57 UTC, SourceR85 commented on packages/node_modules/pouchdb-selector-core/src/utils.js
> +    return
It makes more sense to me to define the return type explicitly:
```suggestion
    return undefined;
```

2024-03-05 20:14 UTC, SourceR85 commented
Assumption is wrong; this would break pouchdb.
Since it needs more work and the author isn't active, I suggest to abandon this patch.

2024-03-15 13:56 UTC, closed without merging