Don't include leveldown in browsers
pouchdb/pouchdb pull request #8187
Opened 2020-09-23 02:31 UTC by RangerMauve

I'm getting errors trying to use this in browser environments due to the migrate.js script always requiring leveldown.

This will cue Webpack and Browserify to ignore that module.

2020-11-22 22:43 UTC, daleharvey requested changes
This is part of the codebase I am least familiar with and will be looking to be doing major improvements on soon, but if it fixes it for you and doesnt break the tests I will be happy to merge.

The tests were broken at the time you submitted but if you rebase we should be able to see if its green. Sorry for the delay and thanks for the patch

2020-12-13 21:20 UTC, RangerMauve commented
@daleharvey Thank you for your patience, just did a rebase.

2020-12-14 14:10 UTC, daleharvey commented
No worries thanks for the update, all passing now 👍

2020-12-14 14:10 UTC, daleharvey approved these changes

2020-12-14 14:11 UTC, merged