Update bulkDocs.js
pouchdb/pouchdb pull request #8211
Opened 2020-10-16 18:20 UTC by msotnikov

Error is not defined. I guess it was meant the `txn.error`

2020-10-16 18:21 UTC, msotnikov commented
https://github.com/pouchdb/pouchdb/issues/8209

2020-10-27 07:54 UTC, msotnikov commented
Are there maintainers here?

2020-11-22 23:17 UTC, daleharvey requested changes
Hey. Very sorry for the delay in reviewing this, had a bit of a break for a while but will be looking to keep up with upcoming changes.

Good catch, the change looks good to me I can see other idb code accessing txn.error. However the repo was broken when you submitted this which is why the tests arent passing. I think this is ok to merge but would like to make sure with a green build so if you could rebase this PR it would be a great help, thanks

2020-11-29 14:26 UTC, daleharvey commented
So error here actually is defined @ https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-indexeddb/src/bulkDocs.js#L28

Its assigned a value in some error conditions which you can see @
https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-indexeddb/src/bulkDocs.js#L244

This is to ensure the transaction has closed before we return, there are situations where the transaction can abort and the error is null, in that case we should probably fall back better, but this isnt correct as is

2020-11-29 14:26 UTC, closed without merging

2020-12-01 21:55 UTC, msotnikov commented
May be solution is wrong, but error still occurs.