(#8222) - fix multiple $regex conditions on same field when using $and
pouchdb/pouchdb pull request #8223
Opened 2020-11-13 00:15 UTC by AlansCodeLog

Fixes #8222 / #6260

This takes the same approach as the `$ne` operator, placing the values to match in an array so they must all match if `$and` is used.

One thing I noticed but did not fix is that in the [couchdb docs](https://docs.couchdb.org/en/stable/api/database/find.html#condition-operators) it says `$regex` can only match against strings. But there is no check for this, regexes have always been able to match against whatever javascript can match. I looked quickly at the other operators, and for example, it seems `$size` too, does not check it's value is an array. Is a fix to conform more to how couchdb handles the conditions wanted? I can submit a separate PR.

2020-11-22 22:19 UTC, daleharvey commented
Yeh if we can align more closely with CouchDB then it leaves less of a chance for users to be surprised when code works with a local backend but not a CouchDB one. 

This code looks good to me, apologies for the delay and the errors, we have removed saucelabs from the travis run so if you rebase then we will have a good idea if this is good to merge. Many thanks

2020-11-22 23:05 UTC, daleharvey requested changes
Meant to flag as requesting changes to keep track

2020-11-24 13:16 UTC, daleharvey approved these changes

2020-11-24 13:17 UTC, daleharvey commented
Awesome thank you

2020-11-24 13:17 UTC, merged

2020-11-24 18:07 UTC, AlansCodeLog commented
Thanks and cool, I'll start working on the other stuff and open up an issue to discuss it.