Add pouchdb-adapter-hyperbee
pouchdb/pouchdb pull request #8267
Opened 2021-01-26 00:48 UTC by RangerMauve

This acts kinda like a leveldown storage adapter, except any indexes you create can be sparsely queried by remote peers without having to do a full replication pass.

2021-01-31 21:27 UTC, daleharvey requested changes
Looks like a great project, thanks for the add, happy to merge once we fix up the typo

2021-01-31 21:27 UTC, daleharvey commented on docs/external.md
> +Sparesely load data from Hyperbee over p2p networks in Node and the Browser.
Sorry little type here? "Sparsely"

2021-02-11 23:23 UTC, RangerMauve commented on docs/external.md
> +Sparesely load data from Hyperbee over p2p networks in Node and the Browser.
Thanks! Fixed.

2021-03-06 08:59 UTC, daleharvey approved these changes
Great cheers

2021-03-06 08:59 UTC, merged

2021-03-07 02:58 UTC, RangerMauve commented
Thank you 😁