Add checkpoint events during replication
pouchdb/pouchdb pull request #8324
Opened 2021-07-09 13:36 UTC by AlbaHerrerias

The motivation behind this PR is to emit checkpoint events during the replication process. This PR is related to @chrisekelley 's [fork](https://github.com/chrisekelley/pouchdb/pull/1). Our goal is to extract and provide test for these functionalities. 

In this PR:
- Add emit event `checkpoint` inside the package `pouchdb-replication`. 
We emit an object, which can contain the following property names: `checkpoint`, `diffing`, `start_next_batch` and `pending_batch`. Would these follow `PouchDB` variable name conventions? We will be happy to refactor them if someone comes up with better naming for these.
- Add test inside `test.replication_events.js`, but we are unsure if this is the correct suite to test it.

Any help would be highly appreciated. Thank you.

2021-07-27 10:41 UTC, AlbaHerrerias commented
We have updated eslint `ecmaVersion` to 8 in order to use async/await in tests. This commit is from [this PR](https://github.com/pouchdb/pouchdb/pull/8321).

2021-08-03 10:31 UTC, janl requested changes

2021-08-03 10:31 UTC, janl commented on packages/node_modules/pouchdb-replication/src/replicate.js
> +      returnValue.emit('checkpoint', { 'diffing': change });
slight preference for calling this `revs_diff` as that’s what the CouchDB API for this is called.

2021-08-03 15:50 UTC, janl approved these changes

2021-08-03 15:51 UTC, merged