fix: store partial_filter_selector in ddoc
pouchdb/pouchdb pull request #8523
Opened 2022-06-17 18:50 UTC by Terreii

This pull request fixes #8522.

2022-06-17 21:03 UTC, Terreii commented
Now only indexeddb adapter fails. I will look into it, on Sunday.

2022-06-18 09:57 UTC, Terreii commented
OK, indexeddb adapter implements its own [query interface](https://github.com/pouchdb/pouchdb/blob/9519c748c48cbac41451039765c758e5987bbc57/packages/node_modules/pouchdb-adapter-indexeddb/src/index.js#L129) (which is used by find).
It only uses the [fields to find an index](https://github.com/pouchdb/pouchdb/blob/9519c748c48cbac41451039765c758e5987bbc57/packages/node_modules/pouchdb-adapter-indexeddb/src/find.js#L139). Those indexes are [native indexes](https://github.com/pouchdb/pouchdb/blob/9519c748c48cbac41451039765c758e5987bbc57/packages/node_modules/pouchdb-adapter-indexeddb/src/setup.js#L43), and they only [don't support filtering](https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/createIndex).
So I might have to create a fields array with the `partial_filter_selector` included and combine it with the user-provided fields-array.

2022-07-12 23:18 UTC, Terreii commented
Sorry for the long silence.
I fixed it by adding to `_customFindAbstractMapper` a third argument: The standard/original `findAbstractMapper`. And then in the _indexeddb adapter_, I added a check if a view has a `partial_filter_selector`. And if so use the standard mapper (a fallback).

2022-07-25 12:13 UTC, Terreii commented
@pouchdb OK Pull request is refactored, squashed, and all tests pass!
I think it is ready to review/merge.

2022-11-11 17:34 UTC, Terreii commented
@AlbaHerrerias I think this pull request is ready for merging.

2022-11-20 19:48 UTC, garbados approved these changes
LGTM!

2022-11-21 11:41 UTC, janl commented
> In other words: find indexes with a partial_filter_selector are on indexeddb adapter db (like on all other adapters) just like map-reduce-views.

We should flag that in the docs then, that using partial filters on `indexeddb` will negate any of the perf benefits of native indexes (arguable one of the two prime reasons for `indexeddb`’s existence :)

2022-11-22 09:45 UTC, Terreii commented
I did add a warning.
Once this pr is merged, I will open an Issue, for finding a way to fix performance in the indexeddb-adapter. Which will be complicated, a reason why I didn't do it in a bug fix.

2022-11-22 10:07 UTC, Terreii commented
OK, I think __test.bulk_docs.js-http #3062 bulkDocs with staggered seqs__ is on pouchdb-server unstable.

2022-11-22 11:45 UTC, janl requested changes

2022-11-22 11:45 UTC, janl commented on docs/_includes/api/create_index.html
> +a`partial_filter_selector` will fallback to using [map-reduce](#query_database),
```suggestion
a`partial_filter_selector` will fall back to using [map-reduce](#query_database),
```

2022-11-22 11:45 UTC, janl commented on docs/_includes/api/create_index.html
> +instead of the native indexes. Negating all index performance gains from the
```suggestion
instead of the native indexes, negating all index performance gains from the
```

2022-11-22 11:46 UTC, janl commented
>  for finding a way to fix performance in the indexeddb-adapter.

I’d be curious to know how you think this can be fixed :)

2022-11-22 13:40 UTC, Terreii commented
> > for finding a way to fix performance in the indexeddb-adapter.
> 
> I’d be curious to know how you think this can be fixed :)

At the moment only by trying to translate filters into indexes, and some into the selectors on query-time. With a fall back to map-reduce if that doesn't work.

But the more I think about it, the more I remember why I droped that path in this fix.

...or it may could act as an use case for a proposal to add partial indexes to IndexedDB indexes (after all SQLite [has them](https://www.sqlite.org/partialindex.html), too).

2022-11-22 16:23 UTC, janl commented
I like your thinking :D

2022-11-23 08:36 UTC, merged