tests/performance: fix use of this.iterations in setup/tearDown
pouchdb/pouchdb pull request #8777
Opened 2023-10-10 12:46 UTC by alxndrsn

Currently, setting `ITERATIONS` to anything except 0 will silently break `pull-replication-perf-skimdb` because of a mismatch between `this.iterations` in the test `setup()` function and the actual number of iterations the test is run for.

This failure is surfaced by https://github.com/pouchdb/pouchdb/pull/8768.

As noted in `TODO` comment, the fix in this commit is not ideal, as it mutates the `testCase` objects created in `tests/performance/perf.basics.js` and other perf test files.

2023-10-10 12:47 UTC, alxndrsn commented
See:

https://github.com/pouchdb/pouchdb/blob/b0f2e57df165368deaffdc4a8765bff4555bdbea/tests/performance/perf.basics.js#L263-L265

2023-10-19 07:43 UTC, garethbowen requested changes
It feels a bit confusing right now. A few suggestions inline...

2023-10-19 07:43 UTC, garethbowen commented on tests/performance/utils.js
> +      testCase.iterations = iterations;
This seems like a risky property name as it's likely to conflict but I can't figure out if you're internationally overwriting a property that's in the testCase? If not, can we call it something that's clearly bespoke?

2023-10-19 07:43 UTC, garethbowen commented on tests/performance/utils.js
> +  if (typeof iterations === 'number') {
Let's default `testCase.iterations` to 0 rather than leaving it undefined.

2023-11-06 09:24 UTC, alxndrsn commented
@garethbowen maybe worth another look: I've updated to pass `iterations` as an argument to the performance test `setup()` function.

2023-11-06 19:37 UTC, garethbowen approved these changes
Thanks! Ship it.

2023-11-08 10:46 UTC, merged