pouchdb-find: make _design/ prefix removal more specific
pouchdb/pouchdb pull request #8946
Opened 2024-04-29 19:58 UTC by alxndrsn

Current code will match `_design/` anywhere.

I suspect it should only be replacing `_design/` when it's a prefix...

2024-04-30 05:31 UTC, garethbowen requested changes

2024-04-30 05:31 UTC, garethbowen commented on packages/node_modules/pouchdb-find/src/adapters/local/utils.js
> -    return name.replace('_design/', '');
Consider caching the regex.

2024-05-08 10:18 UTC, alxndrsn commented on packages/node_modules/pouchdb-find/src/adapters/local/utils.js
> -    return name.replace('_design/', '');
Done

2024-05-08 11:02 UTC, garethbowen approved these changes

2024-05-09 11:38 UTC, merged